### ISSUE TITLE
Footer links not rendering due to use of verbatim

### ISSUE THREAD

**Issue by toddprouty** [nystudio107/devmode#10]
Hey Andrew, just happened to notice `{{ footer.privacyPolicy }}{{ footer.termsOfService }}` in the footer of the site. Looks like [`verbatim` tags are the culprit](https://github.com/nystudio107/devmode/blob/ff064f8af2daa58ae9dd26795b0578e1e1d029a8/cms/templates/_partials/info-footer.twig#L15-L17).

**Comment by jonathanmelville** [comment]
@toddprouty I think this is likely an intentional part of the design rather than a bug.

**Comment by toddprouty** [comment]
@jonathanmelville Ah, you're right. I should have taken a closer look before being "helpful."

**Comment by khalwat** [comment]
yep, bad programmer humour :)
