### ISSUE TITLE
Unable to play podcast with ad-block enabled.

### ISSUE THREAD

**Issue by jessycormier** [nystudio107/devmode#11]
Hey, I thought I would share an issue I've found trying to play one of the podcast shows.

When I have my ublock chrome plugin enabled the podcast play button and play isn't working.

![image](https://user-images.githubusercontent.com/1643234/130837151-f606f9eb-9974-4556-bdb4-642fa2bbff44.png)

**Comment by khalwat** [comment]
The error message for the fetch event is cut off; can you paste in the full text of it?

I'm assuming everything works as expected if ublock is not running, or the devMode site is whitelisted?

**Comment by jessycormier** [comment]
Better Screenshot for you
![image](https://user-images.githubusercontent.com/1643234/130847499-8c30c115-97bb-4f2b-914a-7a2f0914ca95.png)

And some of those bottom errors opened up so you can get an idea of what files.
![image](https://user-images.githubusercontent.com/1643234/130847850-441cc8f5-0be7-4dbe-8ad5-ca4be9347245.png)

this is the plugin: https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm

**Comment by khalwat** [comment]
So everything works without the ublock plugin installed, or if you whitelist devmode.fm with the plugin?

**Comment by jessycormier** [comment]
That's correct; That's how I validated that it was the plugin causing the issue. I quickly looked over the `src/vue/DevmodePlayer.vue` code and honestly, there's nothing that seems like it should throw an error. 

Most likely, uBlock is triggering on some kind of tracking on the MP3 being played which cancels out some functionality or something. 

_p.s. As a user of the plugin, I know this is the case for some other websites I visit and I've come to expect this._

**Comment by khalwat** [comment]
Yeah it's probably the Chartable link that we use to track plays. While we could remove it I suppose, it is useful information to know how many people are playing the podcast.

**Comment by khalwat** [comment]
I've removed chartable entirely, so this should no longer be an issue.
